# Generated by Django 4.1.5 on 2023-01-05 17:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("promo_url", models.TextField()),
                ("description", models.CharField(max_length=256)),
            ],
        ),
    ]
