# Generated by Django 4.1.5 on 2023-01-05 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="promotion",
            name="shiny_meter",
        ),
    ]
