# Generated by Django 4.1.5 on 2023-01-05 13:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0002_remove_promotion_shiny_meter"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="promotion",
            options={},
        ),
        migrations.AlterField(
            model_name="promotion",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
