# Generated by Django 4.1.5 on 2023-01-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("friends", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="friend",
            name="username",
            field=models.CharField(default=None, max_length=32),
            preserve_default=False,
        ),
    ]
