# Generated by Django 4.1.5 on 2023-01-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("friends", "0002_friend_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friend",
            name="friend_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="friend",
            name="friend_name",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
