# Generated by Django 4.1.5 on 2023-01-04 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page', models.CharField(choices=[('Home', 'Home'), ('Profile', 'Profile'), ('Games', 'Games'), ('Promotions', 'Promotions'), ('Friends', 'Friends'), ('Settings', 'Settings'), ('Bug report', 'Bug Report')], default='Home', max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugs_report', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
