# Generated by Django 4.1.5 on 2023-01-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bug_report", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bugreport",
            name="page",
            field=models.CharField(
                choices=[
                    ("Login", "Login"),
                    ("Register", "Register"),
                    ("Home", "Home"),
                    ("Profile", "Profile"),
                    ("Games", "Games"),
                    ("Promotions", "Promotions"),
                    ("Friends", "Friends"),
                    ("Settings", "Settings"),
                    ("Bug report", "Bug Report"),
                ],
                default="Home",
                max_length=20,
            ),
        ),
    ]
