# Generated by Django 4.1.5 on 2023-01-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=23)),
                ('image_url', models.TextField()),
                ('platform', models.CharField(max_length=16)),
            ],
        ),
    ]
