# Generated by Django 4.1.5 on 2023-01-05 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("custom_games", "0004_alter_customgames_user"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="customgames",
            unique_together={("name", "platform")},
        ),
    ]
