# Generated by Django 4.1.5 on 2023-01-05 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rate_log", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rate_log",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rate",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
